### ISSUE TITLE
the file "npm" doesn't exist

### ISSUE THREAD

**Issue by steveblue** [little-green-man/nova-taskfinder#5] opened 2020-10-30 05:03 UTC
First off, this extension is an excellent idea. I expected Nova to provide this kind of functionality out of the box.

I installed the extension and Nova immediately picked up all my project's scripts from the package.json. I select one option and click the run button and this Error appears. The file "npm" doesn't exist. Commands run fine in the Terminal.

Nova 2.1

<img width="836" alt="Screen Shot 2020-10-29 at 10 01 15 PM" src="https://user-images.githubusercontent.com/1171943/97661685-4ac45580-1a32-11eb-86e5-5a2cb826913c.png">

**Comment by kurucu** [comment] 2020-10-30 23:00
Hi Steve. Thanks for reporting this, I'm updating to 2.1 and will try and reproduce!

**Comment by kurucu** [comment] 2020-11-01 03:05
I'm afraid I can't reproduce this.

@steveblue could you please check that you have provided the path to npm correctly? There is a setting for the extension - it should correspond with what you see if you run `which npm` in the terminal.

**Comment by steveblue** [comment] 2020-11-01 19:06
Ah, I believe the issue stems from using nvm. I have to switch between several versions of node throughout any given day.

nvm path is different than `/usr/local/bin/npm`. 

If I set the fields in the Project settings to `which npm` and restart the app, the extension works! Thank you. 

Is there a way for the extension to pickup usage of nvm automatically? I suppose setting this at the project level is an OK solution, but it seems like the extension should "just work".

**Comment by kurucu** [comment] 2020-11-02 01:21
Hi Steve,

Thanks for the update. I'm not sure if I am able to get the output of a command through the Nova extensions API, but could give it a go.

For some reason the environment isn't loaded with shell commands - which I think would solve this whole problem. I've submitted a help ticket to Panic to understand that in more detail.

Both of those could help this work automagically - I'll update the instructions to make it clearer in the meantime.

I'll leave the issue open until we're happy about the way forward. PR's are always open if you have ideas ;)

**Comment by kurucu** [comment] 2022-01-23 00:58
Hi all. Closing this, as I think the issue is fixed. Feel free to re-open if you find more examples/information.

**Closed by kurucu** 2022-01-23 00:58 UTC

**Comment by shrop** [comment] 2022-06-14 19:46
I am having the same issue with npm not found, while using nvm. What was the fix? Thanks!

**Comment by shrop** [comment] 2022-06-14 19:50
I think I got it. I set the path in Project Settings and restarted Nova like above. Thanks all!

**Comment by kurucu** [comment] 2022-06-15 01:31
> I think I got it. I set the path in Project Settings and restarted Nova like above. Thanks all!

Excellent. You can set it globally (Extension Settings) or per project (Project Settings), which overrides the global one, when set.

If you have any further trouble - please let me know!

**Comment by kurucu** [comment] 2022-06-15 01:32
I don't think I can handle the error, as it's passed to Nova by that point, but will look at a way to prompt the user to do this on first installation.
